//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERT_CFG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALERT_CFG()
        {
            this.CONDITION = new HashSet<CONDITION>();
        }
    
        public string id { get; set; }
        public Nullable<int> module_id { get; set; }
        public string message { get; set; }
        public string type { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> shared { get; set; }
        public Nullable<bool> sms { get; set; }
        public Nullable<bool> email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONDITION> CONDITION { get; set; }
    }
}
