//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASS_COD_CUL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASS_COD_CUL()
        {
            this.CULTURE_LIB = new HashSet<CULTURE_LIB>();
        }
    
        public int id { get; set; }
        public int codval_id { get; set; }
        public int culture_id { get; set; }
    
        public virtual CODVAL CODVAL { get; set; }
        public virtual CULTURE CULTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CULTURE_LIB> CULTURE_LIB { get; set; }
    }
}
