//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASS_USE_ALERT
    {
        public int id { get; set; }
        public int alert_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public bool seen { get; set; }
        public bool deleted { get; set; }
        public bool sync { get; set; }
    }
}
