//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOX : DEVICE
    {
        public Nullable<bool> @default { get; set; }
        public int account_id { get; set; }
        public string ip_address { get; set; }
        public bool is_local { get; set; }
        public bool state { get; set; }
        public string serial { get; set; }
        public bool registred { get; set; }
        public bool updated { get; set; }
        public string server_ip { get; set; }
    }
}
