//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFGDEVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFGDEVICE()
        {
            this.MODULEs = new HashSet<MODULE>();
        }
    
        public int id { get; set; }
        public int account_id { get; set; }
        public string ip_address { get; set; }
        public bool is_local { get; set; }
        public bool state { get; set; }
        public string icon { get; set; }
        public string serial { get; set; }
        public bool registred { get; set; }
        public bool updated { get; set; }
        public string server_ip { get; set; }
        public int sync { get; set; }
        public Nullable<bool> def { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODULE> MODULEs { get; set; }
    }
}
