//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFGRADIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFGRADIO()
        {
            this.MODULEs = new HashSet<MODULE>();
        }
    
        public int id { get; set; }
        public int device_id { get; set; }
        public string current_digital_mask { get; set; }
        public string current_analog_mask { get; set; }
        public string analog_mask { get; set; }
        public string digital_mask { get; set; }
        public string address { get; set; }
        public string io { get; set; }
        public int sync { get; set; }
        public decimal battery_level { get; set; }
        public bool is_connected { get; set; }
        public int db { get; set; }
    
        public virtual MODULE MODULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODULE> MODULEs { get; set; }
    }
}
