//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDITION_PART
    {
        public int id { get; set; }
        public Nullable<int> sensor_cond_id { get; set; }
        public Nullable<int> relay_cond_id { get; set; }
        public Nullable<int> time_cond_id { get; set; }
        public Nullable<int> complex_cond_id { get; set; }
        public bool security { get; set; }
    }
}
