//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CULTURE_LIB
    {
        public int id { get; set; }
        public int asscodcul_id { get; set; }
        public string lib { get; set; }
    
        public virtual ASS_COD_CUL ASS_COD_CUL { get; set; }
    }
}
