//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESIGN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DESIGN()
        {
            this.DESIGN_PART = new HashSet<DESIGN_PART>();
            this.DESIGN1 = new HashSet<DESIGN>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string parent_id { get; set; }
        public byte[] data { get; set; }
        public byte[] png { get; set; }
        public Nullable<bool> def { get; set; }
        public Nullable<bool> sync { get; set; }
        public string device_id { get; set; }
        public string parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESIGN_PART> DESIGN_PART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESIGN> DESIGN1 { get; set; }
        public virtual DESIGN DESIGN2 { get; set; }
    }
}
