//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESIGN_PART
    {
        public string id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string design_id { get; set; }
        public string detail_id { get; set; }
        public Nullable<bool> sync { get; set; }
        public string parent { get; set; }
    
        public virtual DESIGN DESIGN { get; set; }
    }
}
