//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABILITY
    {
        public int id { get; set; }
        public string type { get; set; }
        public bool can_see { get; set; }
        public bool can_upd { get; set; }
        public bool can_add { get; set; }
        public bool can_del { get; set; }
    }
}
