//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREFERENCE
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> enabled { get; set; }
        public int culture_id { get; set; }
        public string comment { get; set; }
        public string themes { get; set; }
        public bool cfg_save { get; set; }
        public bool activity_save { get; set; }
        public bool activity_log { get; set; }
        public bool refresh_auto { get; set; }
        public bool n_sms { get; set; }
        public bool n_mail { get; set; }
        public int sync { get; set; }
    
        public virtual CULTURE CULTURE { get; set; }
    }
}
