//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEQ_NUMBER
    {
        public string sequence_name { get; set; }
        public long sequence_increment { get; set; }
        public long sequence_min_value { get; set; }
        public decimal sequence_max_value { get; set; }
        public Nullable<decimal> sequence_cur_value { get; set; }
        public bool sequence_cycle { get; set; }
    }
}
