//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEQUENCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEQUENCE()
        {
            this.TASKs = new HashSet<TASK>();
            this.SEQUENCEs = new HashSet<SEQUENCE>();
        }
    
        public string id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string steady_sequence_id { get; set; }
        public string cycle_id { get; set; }
    
        public virtual CYCLE CYCLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEQUENCE> SEQUENCEs { get; set; }
        public virtual SEQUENCE SEQUENCE1 { get; set; }
    }
}
