//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE
    {
        public int id { get; set; }
        public int module_id { get; set; }
        public int priority { get; set; }
        public string name { get; set; }
        public Nullable<int> action_id { get; set; }
        public string type_cmp { get; set; }
        public string value { get; set; }
        public string prefix { get; set; }
        public string suffix { get; set; }
        public bool inc_val { get; set; }
        public bool shared { get; set; }
        public int sync { get; set; }
    }
}
