//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STATE()
        {
            this.ASS_MOD_STA = new HashSet<ASS_MOD_STA>();
        }
    
        public int id { get; set; }
        public int module_id { get; set; }
        public int priority { get; set; }
        public string name { get; set; }
        public Nullable<int> action_id { get; set; }
        public string type_cmp { get; set; }
        public string value { get; set; }
        public string prefix { get; set; }
        public string suffix { get; set; }
        public bool inc_val { get; set; }
        public int user_id { get; set; }
        public bool shared { get; set; }
        public int sync { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASS_MOD_STA> ASS_MOD_STA { get; set; }
    }
}
