//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYNC
    {
        public int id { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string Object { get; set; }
        public int ObjectId { get; set; }
        public string Action { get; set; }
        public string Query { get; set; }
        public int Done { get; set; }
    }
}
