CREATE TABLE [dbo].[ASS_MOD_HAB] (
    [id]          INT IDENTITY (1, 1) NOT NULL,
    [module_id]   INT NOT NULL,
    [hability_id] INT NOT NULL,
    [sync]        INT NOT NULL,
    CONSTRAINT [PK_ASS_MOD_HAB] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_ASS_MOD_HAB_HABILITY1] FOREIGN KEY ([hability_id]) REFERENCES [dbo].[HABILITY] ([id]),
    CONSTRAINT [fk_ASS_MOD_HAB_MODULE1] FOREIGN KEY ([module_id]) REFERENCES [dbo].[MODULE] ([id])
);


GO
CREATE NONCLUSTERED INDEX [IX_fk_ASS_MOD_HAB_MODULE1]
    ON [dbo].[ASS_MOD_HAB]([module_id] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_fk_ASS_MOD_HAB_HABILITY1]
    ON [dbo].[ASS_MOD_HAB]([hability_id] ASC);

