CREATE TABLE [dbo].[TASK_OLD] (
    [id]         INT           IDENTITY (1, 1) NOT NULL,
    [parent_id]  INT           NULL,
    [name]       VARCHAR (255) NOT NULL,
    [module_id]  INT           NOT NULL,
    [user_id]    INT           NOT NULL,
    [action_id]  INT           NULL,
    [ifc_start]  VARCHAR (10)  NULL,
    [ifc_end]    VARCHAR (10)  NULL,
    [process]    VARCHAR (10)  NULL,
    [state]      VARCHAR (10)  NOT NULL,
    [start]      DATETIME      NOT NULL,
    [end]        DATETIME      NULL,
    [rrule]      VARCHAR (100) NULL,
    [reminder]   VARCHAR (100) NULL,
    [duration]   INT           NULL,
    [comment]    VARCHAR (MAX) NULL,
    [done_start] INT           NOT NULL,
    [done_end]   INT           NOT NULL,
    [sync]       INT           NOT NULL,
    [redit]      VARCHAR (255) NULL,
    [ristart]    VARCHAR (255) NULL,
    [rsstart]    VARCHAR (255) NULL,
    [location]   VARCHAR (45)  NULL,
    [notes]      VARCHAR (45)  NULL,
    [url]        VARCHAR (45)  NULL,
    [all_day]    VARCHAR (45)  NULL,
    [app_id]     VARCHAR (45)  NULL,
    CONSTRAINT [PK_TASK_OLD] PRIMARY KEY CLUSTERED ([id] ASC)
);

